export enum RuntimeState {
  IDLE = "IDLE",
  GENERATING = "GENERATING",
  VALIDATING = "VALIDATING",
  NORMALIZING = "NORMALIZING",
  PRELOADING_ASSETS = "PRELOADING_ASSETS",
  INITIALIZING_RUNTIME = "INITIALIZING_RUNTIME",
  READY = "READY",
  RUNNING = "RUNNING",
  PAUSED = "PAUSED",
  ERROR = "ERROR",
  DESTROYED = "DESTROYED",
}
