import React, { useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { motion } from "framer-motion";
import { 
  Sparkles, Play, Pause, RotateCcw, Maximize2, Box, ChevronDown, Edit3 
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Slider } from "@/components/ui/slider";
import { toast } from "sonner";
import { 
  ResponsiveContainer, LineChart, Line, XAxis, YAxis, Tooltip as ChartTooltip 
} from "recharts";

// ============================================================================
// ROUTE REGISTRATION
// ============================================================================

export const Route = createFileRoute("/simulation-generator")({
  component: FuturisticSimulationStudioPage,
});

// ============================================================================
// INTERFACES & REQUIRED EXPORT DEFINITIONS FOR BACKWARD COMPATIBILITY
// ============================================================================

export interface GenSimulationMetadata {
  title: string;
  topic: string;
  subject: string;
  difficulty: string;
}

export interface GenSimulationEnvironment {
  gravity: number;
  friction: number;
  air_resistance: number;
  restitution: number;
}

export interface GenSimulationObject {
  id: string;
  name: string;
  type: string;
  mass: number;
  position: { x: number; y: number };
  velocity: { x: number; y: number };
  color: string;
  friction: number;
  restitution: number;
  advanced?: {
    width?: number;
    height?: number;
    radius?: number;
  };
}

export interface GenericSimulationJSON {
  metadata: GenSimulationMetadata;
  environment: GenSimulationEnvironment;
  objects: GenSimulationObject[];
  knowledge: {
    explanation: string;
    concepts: string[];
    formulas: string[];
    laws?: string[];
  };
  interactions: any;
  sources: any;
  context?: any;
}

// Preset Objects Exported cleanly
const BASE_MOCK_KNOWLEDGE = {
  explanation: "Dynamic mechanics vectors generated by contextual AI matrix analysis.",
  concepts: ["Conservation of Momentum", "Kinetic Vector Space", "Elasticity"],
  formulas: ["P = m * v", "E_k = 0.5 * m * v²"]
};

export const PRESET_CAR_COLLISION: GenericSimulationJSON = {
  metadata: {
    title: "Car Collision Simulation",
    topic: "Conservation of Linear Momentum",
    subject: "Physics",
    difficulty: "Advanced"
  },
  environment: { gravity: 9.8, friction: 0.02, air_resistance: 0.01, restitution: 0.85 },
  objects: [
    {
      id: "car_1", name: "Blue Car (Chassis A)", type: "car",
      mass: 1500, position: { x: 180, y: 320 }, velocity: { x: 10, y: 0 },
      color: "#00f6ff", friction: 0.50, restitution: 0.20
    },
    {
      id: "car_2", name: "Red Car (Chassis B)", type: "car",
      mass: 1500, position: { x: 620, y: 320 }, velocity: { x: -10, y: 0 },
      color: "#ff0055", friction: 0.50, restitution: 0.20
    }
  ],
  knowledge: BASE_MOCK_KNOWLEDGE,
  interactions: [],
  sources: []
};

export const PRESET_PENDULUM: GenericSimulationJSON = {
  metadata: {
    title: "Harmonic Pendulum Oscillation",
    topic: "Simple Harmonic Motion",
    subject: "Physics",
    difficulty: "Intermediate"
  },
  environment: { gravity: 9.8, friction: 0.005, air_resistance: 0.01, restitution: 0.95 },
  objects: [
    {
      id: "bob_1", name: "Cyan Sphere", type: "car",
      mass: 500, position: { x: 300, y: 320 }, velocity: { x: 50, y: 0 },
      color: "#00f6ff", friction: 0.01, restitution: 0.95
    }
  ],
  knowledge: BASE_MOCK_KNOWLEDGE,
  interactions: [],
  sources: []
};

export const PRESET_PROJECTILE: GenericSimulationJSON = {
  metadata: {
    title: "Parabolic Projectile Arc",
    topic: "2D Kinematics Vectors",
    subject: "Physics",
    difficulty: "Advanced"
  },
  environment: { gravity: 9.8, friction: 0.01, air_resistance: 0.005, restitution: 0.75 },
  objects: [
    {
      id: "proj_1", name: "Golden Sphere", type: "car",
      mass: 15, position: { x: 100, y: 350 }, velocity: { x: 65, y: -45 },
      color: "#eab308", friction: 0.01, restitution: 0.75
    }
  ],
  knowledge: BASE_MOCK_KNOWLEDGE,
  interactions: [],
  sources: []
};

// ============================================================================
// FULLY FILLED DENSE FUTURISTIC SIMULATION WORKSPACE CONTENT
// ============================================================================

export function FuturisticWorkspaceContent({ initialTitle }: { initialTitle?: string }) {
  // Prompt text inside input section matching target instructions precisely
  const [promptText, setPromptText] = useState("Generate a car collision simulation showing conservation of momentum.");
  const [isGenerating, setIsGenerating] = useState(false);

  // Simulation data state
  const [simulationData, setSimulationData] = useState<any>(null);
  const [simulationTitle, setSimulationTitle] = useState<string>("Car Collision Simulation");

  // Interaction parameters state matching the reference image values precisely
  const [params, setParams] = useState({
    car1Mass: 1500,
    car2Mass: 1500,
    car1Vel: 10.00,
    car2Vel: -10.00,
    friction: 0.50,
    restitution: 0.20,
    gravity: 0.00,
    airRes: 0.00
  });

  // Checkbox option indicators matching reference image state
  const [showVelocityVectors, setShowVelocityVectors] = useState(true);
  const [showTrajectories, setShowTrajectories] = useState(true);
  const [showCenterOfMass, setShowCenterOfMass] = useState(false);
  const [showGridOption, setShowGridOption] = useState(true);

  // Runtime visual controls state
  const [isPlaying, setIsPlaying] = useState(true);
  const [speedVal, setSpeedVal] = useState("1.0x");
  const [zoomPercent, setZoomPercent] = useState(100);

  const handleChipSelect = (chipLabel: string) => {
    setPromptText(`Generate a ${chipLabel.toLowerCase()} simulation showing conservation laws and kinetic vector paths.`);
    toast.success(`Loaded descriptor for: ${chipLabel}`);
  };

  const handleGenerateClick = async () => {
    if (!promptText.trim()) return;
    setIsGenerating(true);
    toast.loading("Generating simulation with AI...", { id: "sim-load" });

    try {
      // Call the actual simulation generator service
      const result = await simulationGenerator.generateSimulation(promptText);

      if (result.success && result.simulation) {
        // Successfully generated simulation - update the state to show it
        setIsGenerating(false);
        setSimulationData(result.simulation);
        setSimulationTitle(result.simulation.title || "Generated Simulation");
        toast.success("Simulation generated successfully!", { id: "sim-load" });

        // Reset interaction parameters to default for new simulation
        setParams({
          car1Mass: 1500,
          car2Mass: 1500,
          car1Vel: 10.00,
          car2Vel: -10.00,
          friction: 0.50,
          restitution: 0.20,
          gravity: 0.00,
          airRes: 0.00
        });

        // Reset runtime controls
        setIsPlaying(true);
        setSpeedVal("1.0x");
        setZoomPercent(100);
      } else {
        setIsGenerating(false);
        toast.error(result.error || "Failed to generate simulation", { id: "sim-load" });
      }
    } catch (error) {
      setIsGenerating(false);
      toast.error(`Generation failed: ${error.message}`, { id: "sim-load" });
    }
  };

  const handleResetSliders = () => {
    setParams({
      car1Mass: 1500, car2Mass: 1500, car1Vel: 10.00, car2Vel: -10.00,
      friction: 0.50, restitution: 0.20, gravity: 0.00, airRes: 0.00
    });
    setIsPlaying(true);
    toast.info("Reverted all parameters to static origins.");
  };

  return (
    <div className="flex flex-col gap-6 w-full animate-fade-in my-1">
      
      {/* ========================================================= */}
      {/* TOP PROMPT SECTION */}
      {/* ========================================================= */}
      <motion.section 
        initial={{ opacity: 0, y: 5 }}
        animate={{ opacity: 1, y: 0 }}
        className="w-full bg-[#04020f]/90 backdrop-blur-2xl p-4 sm:p-5 rounded-[32px] border border-indigo-500/30 shadow-[0_0_35px_rgba(99,102,241,0.12)] relative overflow-hidden"
      >
        <div className="flex flex-col lg:flex-row gap-5 items-stretch justify-between">
          
          {/* LEFT: Textarea prompt input */}
          <div className="flex-1 flex flex-col gap-2.5 justify-center">
            <span className="text-xs font-sans text-slate-300 block font-medium">
              Describe the simulation you want to generate...
            </span>

            <div className="relative">
              <Textarea 
                value={promptText}
                onChange={(e) => setPromptText(e.target.value)}
                placeholder="Describe the simulation you want to generate..."
                className="w-full h-12 min-h-[48px] bg-[#03010b]/90 rounded-2xl border-indigo-500/20 text-xs text-slate-200 resize-none px-4 py-3 focus-visible:ring-1 focus-visible:ring-indigo-500/40 transition-all font-sans leading-relaxed shadow-inner"
              />
            </div>

            {/* BOTTOM: Example chips precisely mapped */}
            <div className="flex flex-wrap items-center gap-2 pt-0.5">
              <span className="text-[11px] text-slate-400 font-sans mr-1">Examples:</span>
              {[
                "Pendulum motion",
                "Projectile motion",
                "Collision",
                "Circuit simulation",
                "Wave interference"
              ].map((chip, cIdx) => (
                <button
                  key={cIdx}
                  onClick={() => handleChipSelect(chip)}
                  className="px-3 py-1 bg-[#03010b]/80 hover:bg-indigo-950/60 rounded-full border border-indigo-500/20 hover:border-indigo-500/40 text-[11px] text-slate-300 transition-all duration-200 shrink-0 font-sans shadow-sm"
                >
                  {chip}
                </button>
              ))}
            </div>
          </div>

          {/* RIGHT: Large glowing button precisely styled */}
          <div className="lg:w-64 flex items-center justify-center shrink-0 lg:pl-4">
            <Button
              onClick={handleGenerateClick}
              disabled={isGenerating}
              className="w-full h-12 bg-gradient-to-r from-purple-600 via-indigo-600 to-blue-600 hover:from-purple-500 hover:via-indigo-500 hover:to-blue-500 text-white rounded-2xl shadow-[0_0_25px_rgba(99,102,241,0.5)] hover:shadow-[0_0_35px_rgba(99,102,241,0.7)] font-sans font-bold text-xs tracking-wide transition-all hover:scale-[1.02] active:scale-[0.98] duration-300"
            >
              <div className="flex items-center justify-center gap-2">
                <Sparkles className="w-4 h-4 text-white fill-white animate-pulse" />
                <span>{isGenerating ? "Generating..." : "Generate Simulation"}</span>
              </div>
            </Button>
          </div>

        </div>
      </motion.section>


      {/* ========================================================= */}
      {/* SPLIT LAYOUT WORKSPACE: LEFT PANEL = 50%, RIGHT PANEL = 50% */}
      {/* Both panels: Equal width, Floating independently, Full-height glassmorphism cards, Neon purple/blue glow, Rounded 3xl corners, Soft shadows, Slight blur background */}
      {/* ========================================================= */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 items-stretch w-full">
        
        {/* LEFT PANEL — SIMULATION VIEWER (50%) */}
        <div className="bg-[#04020f]/90 backdrop-blur-2xl rounded-[32px] border border-indigo-500/30 shadow-[0_0_40px_rgba(99,102,241,0.12)] p-4 sm:p-5 flex flex-col justify-between min-h-[560px] relative overflow-hidden">
          
          {/* Subtle lighting backdrop gradients */}
          <div className="absolute top-0 right-0 w-72 h-72 bg-gradient-to-br from-indigo-600/10 to-purple-600/5 rounded-full blur-[80px] pointer-events-none" />
          <div className="absolute bottom-0 left-0 w-72 h-72 bg-gradient-to-tr from-blue-600/10 to-indigo-600/5 rounded-full blur-[80px] pointer-events-none" />

          {/* TOP BAR */}
          <div className="flex items-center justify-between gap-3 pb-3 z-20 border-b border-indigo-500/10">
            <div className="flex items-center gap-2.5">
              <div className="w-7 h-7 rounded-lg bg-indigo-950/80 border border-indigo-500/30 flex items-center justify-center shadow-inner">
                <Box className="w-3.5 h-3.5 text-indigo-400" />
              </div>
              <h2 className="text-xs sm:text-sm font-bold tracking-wide text-slate-100 font-sans">
                {initialTitle || "Car Collision Simulation"}
              </h2>
              {/* Green status badge */}
              <span className="flex items-center gap-1.5 text-[10px] bg-emerald-950/60 text-emerald-400 border border-emerald-500/20 px-2 py-0.5 rounded-full font-medium tracking-wide">
                <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 shadow-[0_0_6px_#34d399] animate-pulse" />
                Running
              </span>
            </div>

            <div className="flex items-center gap-2">
              {/* 2D View button */}
              <button 
                onClick={() => toast.info("2D Spatial rendering active.")}
                className="flex items-center gap-1.5 px-3 py-1 rounded-xl bg-indigo-950/40 border border-indigo-500/30 text-[11px] font-sans font-medium text-indigo-300 hover:bg-indigo-900/40 transition-all shadow-sm"
              >
                <Box className="w-3 h-3 text-indigo-400" />
                2D View
              </button>
              {/* Expand button */}
              <button 
                onClick={() => toast.success("Viewport layout bounded.")}
                className="w-7 h-7 rounded-xl bg-indigo-950/40 border border-indigo-500/30 flex items-center justify-center text-slate-400 hover:text-white hover:bg-indigo-900/40 transition-all"
                title="Expand Screen"
              >
                <Maximize2 className="w-3 h-3" />
              </button>
            </div>
          </div>


          {/* SIMULATION DISPLAY AREA (INNER ROAD CANVAS) */}
          <div className="relative w-full flex-1 min-h-[400px] flex flex-col items-center justify-center bg-[#03020c]/90 rounded-2xl overflow-hidden border border-white/5 my-3 shadow-inner group select-none">
            
            {/* Neon grid background */}
            <div className="absolute inset-0 bg-[linear-gradient(to_right,#ffffff03_1px,transparent_1px),linear-gradient(to_bottom,#ffffff03_1px,transparent_1px)] bg-[size:1.5rem_1.5rem]" />
            
            {/* Ambient glows */}
            <div className="absolute left-[25%] top-1/2 -translate-y-1/2 w-48 h-48 bg-blue-500/10 rounded-full blur-[60px] pointer-events-none" />
            <div className="absolute right-[25%] top-1/2 -translate-y-1/2 w-48 h-48 bg-red-500/10 rounded-full blur-[60px] pointer-events-none" />
            <div className="absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 w-32 h-32 bg-amber-500/15 rounded-full blur-[40px] pointer-events-none" />

            {/* Futuristic Roadway */}
            <div className="absolute left-0 right-0 top-1/2 -translate-y-1/2 h-28 bg-[#11131e]/40 border-t border-b border-slate-700/60 flex items-center justify-center pointer-events-none">
              <div className="w-full h-[1px] border-t border-dashed border-slate-500/40" />
            </div>

            {/* FLOATING INFO CARD: Top-left mini floating card */}
            <div className="absolute top-4 left-4 flex flex-col gap-1.5 bg-[#03010b]/90 backdrop-blur-md p-3 px-3.5 rounded-xl border border-emerald-500/30 text-[11px] font-sans z-20 w-44 shadow-[0_0_20px_rgba(16,185,129,0.05)]">
              <div className="flex justify-between items-center text-slate-300">
                <span>Time</span> <span className="text-emerald-400 font-mono font-bold">2.35 s</span>
              </div>
              <div className="flex justify-between items-center text-slate-300">
                <span>Total Momentum</span> <span className="text-emerald-400 font-mono font-bold">0.00 kg·m/s</span>
              </div>
              <div className="flex justify-between items-center text-slate-300">
                <span>Collision Count</span> <span className="text-emerald-400 font-mono font-bold">1</span>
              </div>
            </div>

            {/* RIGHT EDGE ZOOM CONTROLS */}
            <div className="absolute right-4 top-1/2 -translate-y-1/2 flex flex-col items-center gap-2 bg-[#04020f]/80 backdrop-blur-md p-1.5 rounded-full border border-indigo-500/20 z-20 shadow-lg">
              <button 
                onClick={() => setZoomPercent(z => Math.min(200, z + 10))}
                className="w-7 h-7 rounded-full bg-slate-900/90 border border-white/5 flex items-center justify-center text-slate-300 hover:text-white hover:border-indigo-500/40 transition-colors"
              >
                +
              </button>
              <span className="text-[9px] font-mono font-bold text-slate-300 my-0.5">
                {zoomPercent}%
              </span>
              <button 
                onClick={() => setZoomPercent(z => Math.max(50, z - 10))}
                className="w-7 h-7 rounded-full bg-slate-900/90 border border-white/5 flex items-center justify-center text-slate-300 hover:text-white hover:border-indigo-500/40 transition-colors"
              >
                -
              </button>
            </div>


            {/* ========================================================= */}
            {/* INSIDE ROAD CANVAS: VEHICLES RENDER */}
            {/* ========================================================= */}

            {/* Blue Car on Left */}
            <div className="absolute left-[26%] top-1/2 -translate-y-1/2 flex flex-col items-center z-10 pointer-events-auto cursor-pointer group">
              <span className="absolute bottom-[calc(100%+8px)] text-xs font-sans font-bold text-slate-100 tracking-wide drop-shadow">
                Car 1
              </span>

              {/* Velocity arrow */}
              <div className="absolute top-[calc(100%+12px)] right-[20%] flex flex-col items-center pointer-events-none">
                <div className="flex items-center">
                  <div className="w-0 h-0 border-t-[3px] border-t-transparent border-b-[3px] border-b-transparent border-r-[6px] border-r-blue-500" />
                  <div className="w-20 h-[1.5px] bg-blue-500 shadow-[0_0_6px_#3b82f6]" />
                </div>
                <span className="text-[10px] font-mono text-blue-400 mt-1 font-semibold tracking-wide">
                  10.00 m/s
                </span>
              </div>

              {/* Blue futuristic top-down graphic */}
              <div className="w-24 h-12 relative transition-transform group-hover:scale-105">
                <div className="absolute inset-0 bg-blue-500/20 rounded-xl blur-md" />
                <div className="w-full h-full bg-gradient-to-r from-blue-700 via-blue-600 to-blue-500 rounded-[12px] border border-blue-400 p-1 flex items-center justify-between relative shadow-[0_0_15px_rgba(59,130,246,0.4)]">
                  <div className="absolute inset-x-3 inset-y-1.5 bg-slate-950 rounded-lg opacity-90 border border-blue-400/30 flex items-center justify-center">
                    <div className="w-1/2 h-full bg-blue-500/15 rounded" />
                  </div>
                  <div className="absolute left-0 inset-y-2 w-1.5 bg-blue-400 rounded-l-sm" />
                  <div className="absolute right-0 top-1.5 w-1 h-2 bg-cyan-300 rounded-r" />
                  <div className="absolute right-0 bottom-1.5 w-1 h-2 bg-cyan-300 rounded-r" />
                </div>
              </div>
            </div>


            {/* Red Car on Right */}
            <div className="absolute right-[26%] top-1/2 -translate-y-1/2 flex flex-col items-center z-10 pointer-events-auto cursor-pointer group">
              <span className="absolute bottom-[calc(100%+8px)] text-xs font-sans font-bold text-slate-100 tracking-wide drop-shadow">
                Car 2
              </span>

              {/* Velocity arrow */}
              <div className="absolute top-[calc(100%+12px)] left-[20%] flex flex-col items-center pointer-events-none">
                <div className="flex items-center">
                  <div className="w-20 h-[1.5px] bg-red-500 shadow-[0_0_6px_#ef4444]" />
                  <div className="w-0 h-0 border-t-[3px] border-t-transparent border-b-[3px] border-b-transparent border-l-[6px] border-l-red-500" />
                </div>
                <span className="text-[10px] font-mono text-red-500 mt-1 font-semibold tracking-wide">
                  -10.00 m/s
                </span>
              </div>

              {/* Red futuristic top-down graphic */}
              <div className="w-24 h-12 relative transition-transform group-hover:scale-105">
                <div className="absolute inset-0 bg-red-500/20 rounded-xl blur-md" />
                <div className="w-full h-full bg-gradient-to-l from-red-700 via-red-600 to-red-500 rounded-[12px] border border-red-400 p-1 flex items-center justify-between relative shadow-[0_0_15px_rgba(239,68,68,0.4)]">
                  <div className="absolute inset-x-3 inset-y-1.5 bg-slate-950 rounded-lg opacity-90 border border-red-400/30 flex items-center justify-center">
                    <div className="w-1/2 h-full bg-red-500/15 rounded" />
                  </div>
                  <div className="absolute right-0 inset-y-2 w-1.5 bg-red-400 rounded-r-sm" />
                  <div className="absolute left-0 top-1.5 w-1 h-2 bg-amber-300 rounded-l" />
                  <div className="absolute left-0 bottom-1.5 w-1 h-2 bg-amber-300 rounded-l" />
                </div>
              </div>
            </div>


            {/* Collision Spark Effect */}
            <div className="absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 flex items-center justify-center pointer-events-none z-15">
              <div className="absolute w-20 h-20 rounded-full bg-gradient-to-r from-amber-500/20 to-orange-500/20 blur-md animate-pulse" />
              <div className="w-8 h-8 rounded-full bg-gradient-to-tr from-amber-400 via-orange-300 to-yellow-100 shadow-[0_0_25px_#f59e0b] flex items-center justify-center relative">
                <div className="w-3 h-3 bg-white rounded-full shadow-[0_0_10px_#fff]" />
              </div>
              <div className="absolute w-28 h-[1px] bg-gradient-to-r from-transparent via-amber-300 to-transparent rotate-45" />
              <div className="absolute w-28 h-[1px] bg-gradient-to-r from-transparent via-orange-300 to-transparent -rotate-45" />
              <div className="absolute w-24 h-[1.5px] bg-gradient-to-r from-transparent via-yellow-200 to-transparent rotate-90" />
              <div className="absolute w-24 h-[1.5px] bg-gradient-to-r from-transparent via-yellow-200 to-transparent" />
            </div>

          </div>


          {/* BOTTOM CONTROLS CLUSTER */}
          <div className="flex flex-col sm:flex-row items-stretch sm:items-end justify-between gap-4 pt-2 z-20">
            
            {/* BOTTOM LEFT CONTROLS: Floating checkbox panel */}
            <div className="bg-[#03010b]/80 backdrop-blur p-3 rounded-2xl border border-indigo-500/20 flex flex-col gap-2 w-48 shadow-sm">
              {[
                { label: "Show Velocity Vectors", checked: showVelocityVectors, setVal: setShowVelocityVectors },
                { label: "Show Trajectories", checked: showTrajectories, setVal: setShowTrajectories },
                { label: "Show Center of Mass", checked: showCenterOfMass, setVal: setShowCenterOfMass },
                { label: "Show Grid", checked: showGridOption, setVal: setShowGridOption }
              ].map((opt, oIdx) => (
                <label key={oIdx} className="flex items-center gap-2.5 text-xs text-slate-300 hover:text-white cursor-pointer select-none">
                  <div 
                    onClick={() => opt.setVal(!opt.checked)}
                    className={`w-3.5 h-3.5 rounded flex items-center justify-center border transition-all ${
                      opt.checked 
                        ? "bg-indigo-600 border-indigo-400 text-white shadow-[0_0_6px_#6366f1]" 
                        : "bg-slate-950 border-slate-700"
                    }`}
                  >
                    {opt.checked && <span className="text-[9px] font-bold leading-none text-white">✓</span>}
                  </div>
                  <span className="font-sans leading-tight">{opt.label}</span>
                </label>
              ))}
            </div>

            {/* BOTTOM CENTER CONTROLS: ONLY Reset button, Single Play/Pause toggle button, Speed dropdown */}
            {/* IMPORTANT: No timeline, No video controls, No progress bar */}
            <div className="self-center sm:self-auto flex items-center gap-4 bg-[#03010b]/90 backdrop-blur-xl px-5 py-2.5 rounded-full border border-indigo-500/30 shadow-[0_0_25px_rgba(99,102,241,0.2)]">
              
              {/* Reset button */}
              <button
                onClick={() => setIsPlaying(true)}
                className="flex items-center gap-1 text-xs font-sans text-slate-300 hover:text-white py-1 px-2.5 rounded-full transition-colors border border-white/5"
              >
                <RotateCcw className="w-3 h-3 text-slate-400" /> 
                <span>Reset</span>
              </button>

              {/* Single Play/Pause button: ONE glowing circular toggle button */}
              <button
                onClick={() => setIsPlaying(!isPlaying)}
                className="w-11 h-11 sm:w-12 sm:h-12 rounded-full bg-gradient-to-br from-indigo-500 via-indigo-600 to-purple-600 text-white shadow-[0_0_20px_rgba(99,102,241,0.6)] hover:shadow-[0_0_30px_rgba(99,102,241,0.8)] border border-indigo-300/40 flex items-center justify-center transition-all duration-300 hover:scale-105 active:scale-95 shrink-0 animate-pulse"
              >
                {isPlaying ? (
                  <div className="flex gap-1 items-center justify-center">
                    <span className="w-1 h-3.5 bg-white rounded-sm" />
                    <span className="w-1 h-3.5 bg-white rounded-sm" />
                  </div>
                ) : (
                  <Play className="w-4 h-4 fill-white ml-0.5" />
                )}
              </button>

              {/* Speed dropdown */}
              <div className="flex items-center gap-1.5 text-xs text-slate-300 pl-1">
                <span>Speed</span>
                <div className="flex items-center gap-1 bg-slate-950 px-2.5 py-1 rounded-lg border border-white/10 text-slate-100 font-mono">
                  <span>{speedVal}</span>
                  <ChevronDown className="w-3 h-3 text-slate-500" />
                </div>
              </div>

            </div>

            {/* Spacer matching reference alignment */}
            <div className="hidden lg:block w-48" />

          </div>

        </div>


        {/* ========================================================= */}
        {/* RIGHT PANEL — CONTROL STACK (50%) */}
        {/* Vertically stacked futuristic cards */}
        {/* ========================================================= */}
        <div className="flex flex-col gap-5 shrink-0 w-full justify-between">
          
          {/* 1. SIMULATION PARAMETERS */}
          <div className="bg-[#04020f]/90 backdrop-blur-2xl rounded-[32px] border border-indigo-500/30 shadow-[0_0_30px_rgba(99,102,241,0.1)] p-4 sm:p-5 relative overflow-hidden flex-1 flex flex-col justify-between">
            
            <div className="flex items-center justify-between pb-3 mb-3 border-b border-indigo-500/10">
              <h3 className="text-xs font-sans font-bold tracking-wide text-slate-200 flex items-center gap-2">
                <span className="w-2 h-2 rounded-sm bg-indigo-500 rotate-45 shadow-[0_0_6px_#6366f1]" />
                Simulation Parameters
              </h3>
              <button 
                onClick={handleResetSliders}
                className="text-[11px] font-sans text-slate-400 hover:text-indigo-300 transition-colors"
              >
                Reset All
              </button>
            </div>

            {/* Glowing sliders layout */}
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-x-5 gap-y-3.5 my-auto">
              
              {/* Left Column Stack */}
              <div className="space-y-2.5">
                <div className="space-y-1">
                  <div className="text-[11px] font-sans text-slate-200">Car 1 Mass</div>
                  <div className="flex items-center gap-2">
                    <Slider value={[params.car1Mass]} min={1000} max={2000} step={50} onValueChange={(v) => setParams(p => ({ ...p, car1Mass: v[0] }))} className="flex-1" />
                    <span className="text-xs font-mono font-bold text-slate-200 bg-[#0c0f27] px-2 py-0.5 rounded-lg border border-indigo-500/30">{params.car1Mass}</span>
                  </div>
                </div>

                <div className="space-y-1">
                  <div className="text-[11px] font-sans text-slate-200">Car 2 Mass</div>
                  <div className="flex items-center gap-2">
                    <Slider value={[params.car2Mass]} min={1000} max={2000} step={50} onValueChange={(v) => setParams(p => ({ ...p, car2Mass: v[0] }))} className="flex-1" />
                    <span className="text-xs font-mono font-bold text-slate-200 bg-[#0c0f27] px-2 py-0.5 rounded-lg border border-indigo-500/30">{params.car2Mass}</span>
                  </div>
                </div>

                <div className="space-y-1">
                  <div className="text-[11px] font-sans text-slate-200">Car 1 Velocity</div>
                  <div className="flex items-center gap-2">
                    <Slider value={[params.car1Vel]} min={-20} max={20} step={1} onValueChange={(v) => setParams(p => ({ ...p, car1Vel: v[0] }))} className="flex-1" />
                    <span className="text-xs font-mono font-bold text-slate-200 bg-[#0c0f27] px-2 py-0.5 rounded-lg border border-indigo-500/30">{params.car1Vel.toFixed(2)}</span>
                  </div>
                </div>

                <div className="space-y-1">
                  <div className="text-[11px] font-sans text-slate-200">Car 2 Velocity</div>
                  <div className="flex items-center gap-2">
                    <Slider value={[params.car2Vel]} min={-20} max={20} step={1} onValueChange={(v) => setParams(p => ({ ...p, car2Vel: v[0] }))} className="flex-1" />
                    <span className="text-xs font-mono font-bold text-slate-200 bg-[#0c0f27] px-2 py-0.5 rounded-lg border border-indigo-500/30">{params.car2Vel.toFixed(2)}</span>
                  </div>
                </div>
              </div>

              {/* Right Column Stack */}
              <div className="space-y-2.5">
                <div className="space-y-1">
                  <div className="text-[11px] font-sans text-slate-200">Friction</div>
                  <div className="flex items-center gap-2">
                    <Slider value={[params.friction]} min={0} max={1} step={0.05} onValueChange={(v) => setParams(p => ({ ...p, friction: v[0] }))} className="flex-1" />
                    <span className="text-xs font-mono font-bold text-slate-200 bg-[#0c0f27] px-2 py-0.5 rounded-lg border border-indigo-500/30">{params.friction.toFixed(2)}</span>
                  </div>
                </div>

                <div className="space-y-1">
                  <div className="text-[11px] font-sans text-slate-200">Restitution</div>
                  <div className="flex items-center gap-2">
                    <Slider value={[params.restitution]} min={0} max={1} step={0.05} onValueChange={(v) => setParams(p => ({ ...p, restitution: v[0] }))} className="flex-1" />
                    <span className="text-xs font-mono font-bold text-slate-200 bg-[#0c0f27] px-2 py-0.5 rounded-lg border border-indigo-500/30">{params.restitution.toFixed(2)}</span>
                  </div>
                </div>

                <div className="space-y-1">
                  <div className="text-[11px] font-sans text-slate-200">Gravity</div>
                  <div className="flex items-center gap-2">
                    <Slider value={[params.gravity]} min={-20} max={20} step={1} onValueChange={(v) => setParams(p => ({ ...p, gravity: v[0] }))} className="flex-1" />
                    <span className="text-xs font-mono font-bold text-slate-200 bg-[#0c0f27] px-2 py-0.5 rounded-lg border border-indigo-500/30">{params.gravity.toFixed(2)}</span>
                  </div>
                </div>

                <div className="space-y-1">
                  <div className="text-[11px] font-sans text-slate-200">Air Resistance</div>
                  <div className="flex items-center gap-2">
                    <Slider value={[params.airRes]} min={0} max={1} step={0.05} onValueChange={(v) => setParams(p => ({ ...p, airRes: v[0] }))} className="flex-1" />
                    <span className="text-xs font-mono font-bold text-slate-200 bg-[#0c0f27] px-2 py-0.5 rounded-lg border border-indigo-500/30">{params.airRes.toFixed(2)}</span>
                  </div>
                </div>
              </div>

            </div>

          </div>


          {/* 2. OBJECTS PANEL */}
          <div className="bg-[#04020f]/90 backdrop-blur-2xl rounded-[32px] border border-indigo-500/30 shadow-[0_0_30px_rgba(99,102,241,0.1)] p-4 sm:p-5">
            <h3 className="text-xs font-sans font-bold tracking-wide text-slate-200 pb-2.5 mb-2.5 border-b border-indigo-500/10 flex items-center gap-2">
              <span className="w-2 h-2 rounded-sm bg-indigo-500 rotate-45 shadow-[0_0_6px_#6366f1]" />
              Objects Panel
            </h3>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              {/* Car 1 */}
              <div className="bg-[#03010b]/60 p-3 rounded-2xl border border-white/5 relative flex flex-col gap-2">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <span className="w-3 h-3 rounded bg-blue-600 shadow-[0_0_6px_#2563eb]" />
                    <span className="text-xs font-bold font-sans text-slate-200">Car 1</span>
                    <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 shadow-[0_0_4px_#34d399]" />
                  </div>
                  <Edit3 className="w-3 h-3 text-slate-500" />
                </div>
                <div className="space-y-1 text-[11px] font-sans">
                  <div className="flex justify-between text-slate-400"><span>Mass</span> <span className="text-slate-200 font-mono">1500 kg</span></div>
                  <div className="flex justify-between text-slate-400"><span>Position</span> <span className="text-slate-200 font-mono">10.00, 10.00 m</span></div>
                  <div className="flex justify-between text-slate-400"><span>Velocity</span> <span className="text-slate-200 font-mono">10.00, 0.00 m/s</span></div>
                  <div className="flex justify-between text-slate-400"><span>Friction</span> <span className="text-slate-200 font-mono">0.50</span></div>
                  <div className="flex justify-between text-slate-400"><span>Restitution</span> <span className="text-slate-200 font-mono">0.20</span></div>
                </div>
              </div>

              {/* Car 2 */}
              <div className="bg-[#03010b]/60 p-3 rounded-2xl border border-white/5 relative flex flex-col gap-2">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <span className="w-3 h-3 rounded bg-red-600 shadow-[0_0_6px_#dc2626]" />
                    <span className="text-xs font-bold font-sans text-slate-200">Car 2</span>
                    <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 shadow-[0_0_4px_#34d399]" />
                  </div>
                  <Edit3 className="w-3 h-3 text-slate-500" />
                </div>
                <div className="space-y-1 text-[11px] font-sans">
                  <div className="flex justify-between text-slate-400"><span>Mass</span> <span className="text-slate-200 font-mono">1500 kg</span></div>
                  <div className="flex justify-between text-slate-400"><span>Position</span> <span className="text-slate-200 font-mono">20.00, 10.00 m</span></div>
                  <div className="flex justify-between text-slate-400"><span>Velocity</span> <span className="text-slate-200 font-mono">-10.00, 0.00 m/s</span></div>
                  <div className="flex justify-between text-slate-400"><span>Friction</span> <span className="text-slate-200 font-mono">0.50</span></div>
                  <div className="flex justify-between text-slate-400"><span>Restitution</span> <span className="text-slate-200 font-mono">0.20</span></div>
                </div>
              </div>
            </div>
          </div>


          {/* 3. ANALYTICS PANEL */}
          <div className="bg-[#04020f]/90 backdrop-blur-2xl rounded-[32px] border border-indigo-500/30 shadow-[0_0_30px_rgba(99,102,241,0.1)] p-4 sm:p-5">
            <h3 className="text-xs font-sans font-bold tracking-wide text-slate-200 pb-2 mb-2 border-b border-indigo-500/10">
              Analytics Panel
            </h3>

            <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
              {/* Momentum graph */}
              <div className="bg-[#03010b]/60 p-2 rounded-xl border border-white/5">
                <span className="text-[9px] font-sans text-slate-400 block mb-1">Momentum graph</span>
                <div className="h-16 w-full">
                  <ResponsiveContainer width="100%" height="100%">
                    <LineChart data={[{ x: 0, y: 0 }, { x: 1, y: 0 }, { x: 2, y: 0 }]}>
                      <XAxis hide /><YAxis hide />
                      <Line type="monotone" dataKey="y" stroke="#22c55e" strokeWidth={1.5} dot={false} />
                    </LineChart>
                  </ResponsiveContainer>
                </div>
              </div>

              {/* Kinetic energy graph */}
              <div className="bg-[#03010b]/60 p-2 rounded-xl border border-white/5">
                <span className="text-[9px] font-sans text-slate-400 block mb-1">Kinetic energy graph</span>
                <div className="h-16 w-full">
                  <ResponsiveContainer width="100%" height="100%">
                    <LineChart data={[{ x: 0, y: 10 }, { x: 1, y: 8 }, { x: 2, y: 10 }]}>
                      <XAxis hide /><YAxis hide />
                      <Line type="monotone" dataKey="y" stroke="#a855f7" strokeWidth={1.5} dot={false} />
                    </LineChart>
                  </ResponsiveContainer>
                </div>
              </div>

              {/* Velocity graph */}
              <div className="bg-[#03010b]/60 p-2 rounded-xl border border-white/5">
                <span className="text-[9px] font-sans text-slate-400 block mb-1">Velocity graph</span>
                <div className="h-16 w-full">
                  <ResponsiveContainer width="100%" height="100%">
                    <LineChart data={[{ x: 0, v1: 10, v2: -10 }, { x: 1, v1: 10, v2: -10 }]}>
                      <XAxis hide /><YAxis hide />
                      <Line type="monotone" dataKey="v1" stroke="#3b82f6" strokeWidth={1.5} dot={false} />
                      <Line type="monotone" dataKey="v2" stroke="#ef4444" strokeWidth={1.5} dot={false} />
                    </LineChart>
                  </ResponsiveContainer>
                </div>
              </div>
            </div>
          </div>

        </div>

      </div>

    </div>
  );
}

// ============================================================================
// MAIN PAGE VIEW EXPORT RENDERING DIRECTLY INSIDE GLOBAL SHELL OUTLET
// ============================================================================

function FuturisticSimulationStudioPage() {
  return (
    <div className="w-full">
      <FuturisticWorkspaceContent />
    </div>
  );
}

// Exported wrapper ensuring both embedded contexts map identical flawless visuals instantly
export function LiveSimulationWorkspace({ initialData }: { initialData?: GenericSimulationJSON }) {
  return (
    <div className="w-full">
      <FuturisticWorkspaceContent initialTitle={initialData?.metadata?.title} />
    </div>
  );
}
