/**
 * Asset Management Hooks for EduSim
 * Provides optimized access to organized asset data
 * Works with objectData.js and categories.json generated by organizeAssets.cjs
 */

import { useMemo } from 'react';
import * as objectDataModule from '../data/objectData';
import { resolveBestAsset, normalizeAssetName } from '../utils/assetCatalogResolver';

const objectData = (objectDataModule as any).default ?? objectDataModule;
import categoriesData from '../data/categories.json';

function buildResolvedAsset(name: string) {
  const exact = objectData[name as keyof typeof objectData];
  if (exact) {
    return exact;
  }

  const resolved = resolveBestAsset(name);
  if (!resolved) {
    return null;
  }

  return {
    key: resolved.id,
    category: resolved.category,
    file: resolved.default || resolved.path,
    image: resolved.default || resolved.path,
    aliases: resolved.aliases || [],
    variants: resolved.variants || [],
    width: 1,
    height: 1,
    mass: 1,
    friction: 0.1,
    bounce: 0.1,
  };
}

/**
 * Get a single asset by name
 * @param name - Asset name (filename without extension)
 * @returns Asset object with image, category, physics properties, or null
 */
export function useAsset(name: string) {
  return useMemo(() => {
    if (!name) {
      return null;
    }
    return buildResolvedAsset(name);
  }, [name]);
}

/**
 * Get all assets in a specific category
 * @param categoryName - Category name (e.g., 'vehicles', 'furniture')
 * @returns Array of asset objects in the category
 */
export function useCategory(categoryName: string) {
  return useMemo(() => {
    if (!categoryName || !categoriesData[categoryName as keyof typeof categoriesData]) {
      return [];
    }

    const assetNames = categoriesData[categoryName as keyof typeof categoriesData];
    return assetNames
      .map((name) => buildResolvedAsset(name))
      .filter((asset) => asset !== undefined);
  }, [categoryName]);
}

/**
 * Get Matter.js physics properties for an asset
 * @param assetName - Asset name
 * @returns Physics properties object with mass, friction, bounce, etc.
 */
export function usePhysics(assetName: string) {
  return useMemo(() => {
    const asset = assetName ? buildResolvedAsset(assetName) : null;

    if (!asset) {
      return null;
    }

    return {
      mass: asset.mass,
      friction: asset.friction,
      frictionAir: 0.001, // Default air friction
      restitution: asset.restitution,
      density: asset.density,
      bounce: asset.bounce,
      properties: {
        mass: asset.mass,
        friction: asset.friction,
        restitution: asset.restitution,
        density: asset.density
      }
    };
  }, [assetName]);
}

/**
 * Search for assets by keyword (name or category)
 * @param query - Search query
 * @returns Array of matching assets
 */
export function useAssetSearch(query: string) {
  return useMemo(() => {
    if (!query || query.trim() === '') {
      return [];
    }

    const lowerQuery = normalizeAssetName(query);
    return Object.entries(objectData)
      .filter(([name, asset]) => {
        return (
          normalizeAssetName(name).includes(lowerQuery) ||
          normalizeAssetName((asset as any).category).includes(lowerQuery)
        );
      })
      .map(([, asset]) => asset as any);
  }, [query]);
}

/**
 * Get all assets from multiple categories
 * @param categoryNames - Array of category names
 * @returns Object with category names as keys and asset arrays as values
 */
export function useMultipleCategories(categoryNames: string[]) {
  return useMemo(() => {
    const result: Record<string, any[]> = {};

    for (const category of categoryNames) {
      result[category] = useCategory(category);
    }

    return result;
  }, [categoryNames]);
}

/**
 * Get dimensions for an asset
 * @param assetName - Asset name
 * @returns Object with width, height, and aspect ratio
 */
export function useAssetDimensions(assetName: string) {
  return useMemo(() => {
    const asset = assetName ? buildResolvedAsset(assetName) : null;

    if (!asset) {
      return null;
    }

    return {
      width: asset.width,
      height: asset.height,
      ratio: asset.width / asset.height
    };
  }, [assetName]);
}

/**
 * Get all categories with metadata
 * @returns Object with category names and their asset counts
 */
export function useCategoryInfo() {
  return useMemo(() => {
    const result: Record<string, { count: number; assets: string[] }> = {};

    for (const [category, assets] of Object.entries(categoriesData)) {
      result[category] = {
        count: assets.length,
        assets: assets
      };
    }

    return result;
  }, []);
}

/**
 * Get all assets with optional filtering
 * @param filter - Optional filter object with minMass, maxMass, or category
 * @returns Array of all assets matching the filter
 */
export function useAllAssets(
  filter?: {
    minMass?: number;
    maxMass?: number;
    category?: string;
  }
) {
  return useMemo(() => {
    let assets = Object.entries(objectData).map(([, asset]) => asset as any);

    if (!filter) {
      return assets;
    }

    if (filter.minMass !== undefined) {
      assets = assets.filter((asset) => asset.mass >= filter.minMass!);
    }

    if (filter.maxMass !== undefined) {
      assets = assets.filter((asset) => asset.mass <= filter.maxMass!);
    }

    if (filter.category !== undefined) {
      assets = assets.filter((asset) => asset.category === filter.category);
    }

    return assets;
  }, [filter]);
}

/**
 * Create a Matter.js body options object for an asset
 * Used in physics simulations
 * @param assetName - Asset name
 * @returns Matter.js body options object
 */
export function usePhysicsEngine() {
  return useMemo(
    () => ({
      getBodyOptions: (assetName: string) => {
        const physics = usePhysics(assetName);
        if (!physics) return null;

        return {
          mass: physics.mass,
          friction: physics.friction,
          frictionAir: physics.frictionAir,
          restitution: physics.restitution,
          density: physics.density,
          label: assetName
        };
      }
    }),
    []
  );
}

// Export all hooks together for convenience
export const assetHooks = {
  useAsset,
  useCategory,
  usePhysics,
  useAssetSearch,
  useMultipleCategories,
  useCategoryInfo,
  useAssetDimensions,
  useAllAssets,
  usePhysicsEngine
};

export default assetHooks;
